# Generated by Django 3.2.15 on 2024-01-31 00:25

from django.db import migrations
from django.db.models import F


def set_price_to_products(apps, schema_editor):
    order_product = apps.get_model('foodcartapp', 'OrderProduct')

    for order in order_product.objects.filter(current_price__isnull=True):
        order.current_price = order.product.price
        order.save()


class Migration(migrations.Migration):
    dependencies = [
        ('foodcartapp', '0041_rename_price_orderproduct_current_price'),
    ]

    operations = [
        migrations.RunPython(set_price_to_products)
    ]
