# Generated by Django 3.2.15 on 2024-02-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20240131_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('create', 'Создан'), ('cooking', 'Готовится'), ('deliver', 'Доставляется'), ('complete', 'Завершен')], default='create', max_length=10, verbose_name='Статус'),
        ),
    ]
