# Generated by Django 3.2.15 on 2024-02-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_auto_20240202_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта')], db_index=True, default='cash', max_length=10, verbose_name='Способ оплаты'),
        ),
    ]
