# Generated by Django 5.0.3 on 2024-03-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_order_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='описание'),
        ),
    ]
